GoAnime/Controllers/AnimeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Linq;
using GoAnime.Core.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using GoAnime.Core.ViewModels;
using System;

namespace GoAnime.Controllers
{
    public class AnimeController : Controller
    {
        private readonly IAnimeService _service;
        public AnimeController(IAnimeService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync(v => v.Studio));
        public async Task<IActionResult> Filter(string searchString) 
        {
            var allAnime = await _service.GetAllAsync(v => v.Studio);
            if (!string.IsNullOrEmpty(searchString))
            {
                var searchResult = allAnime.Where(v => string.Equals(v.Name, searchString, StringComparison.OrdinalIgnoreCase) || string.Equals(v.Description, searchString, StringComparison.OrdinalIgnoreCase) || string.Equals(v.AnimeGenre.ToString(), searchString, StringComparison.OrdinalIgnoreCase)).ToList();
                return View("Index", searchResult);
            }
            return View("Index", allAnime);
        } 

        public async Task<IActionResult> Details(int id) => View(await _service.GetAnimeByIdAsync(id));
        public async Task<IActionResult> Create()
        {
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewAnimeVM anime)
        {
            if (ModelState.IsValid)
            {
                await _service.AddNewAnimeAsync(anime);
                return RedirectToAction(nameof(Index));
            }
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View(anime);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var animeDetails = await _service.GetAnimeByIdAsync(id);
            if (animeDetails == null) return View("NotFound");
            var response = new NewAnimeVM()
            {
                Id = animeDetails.Id,
                Name = animeDetails.Name,
                Description = animeDetails.Description,
                AnimeGenre = animeDetails.AnimeGenre,
                ImageURL = animeDetails.ImageURL,
                Price = animeDetails.Price,
                StartDate = animeDetails.StartDate,
                EndDate = animeDetails.EndDate,
                ProducerId = animeDetails.ProducerId,
                StudioId = animeDetails.StudioId,
                VoiceActorIds = animeDetails.VoiceActors_Anime.Select(v => v.VoiceActorId).ToList()
            };
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewAnimeVM anime)
        {
            if (id != anime.Id) return View("NotFound");
            if (ModelState.IsValid)
            {
                await _service.UpdateAnimeAsync(anime);
                return RedirectToAction(nameof(Index));
            }
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View(anime);
        }
    }
}

GoAnime/Controllers/OrdersController.cs
using GoAnime.Core.CartFunctionality;
using GoAnime.Core.Interfaces;
using GoAnime.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IAnimeService _service;
        private readonly IOrderService _order;
        private readonly Cart _cart;
        public OrdersController(IAnimeService service, Cart cart, IOrderService order)
        {
            _service = service;
            _cart = cart;
            _order = order;
        }
        public async Task<IActionResult> Index() 
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            return View(await _order.GetOrdersByUserIdAndRoleAsync(userId, userRole));
        } 
        public IActionResult Cart() 
        {
            var items = _cart.GetCartItems();
            _cart.CartItems = items;
            var response = new CartVM()
            {
                Cart = _cart,
                CartTotal = _cart.CartTotal()
            };
            return View(response);
        }
        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            var anime = await _service.GetAnimeByIdAsync(id);
            if(anime != null)
            {
                _cart.AddItemToCart(anime);
            }
            return RedirectToAction(nameof(Cart));           
        }

        public async Task<RedirectToActionResult> RemoveFromCart(int id)
        {
            var anime = await _service.GetAnimeByIdAsync(id);
            if (anime != null)
            {
                _cart.RemoveItemFromCart(anime);
            }
            return RedirectToAction(nameof(Cart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);
            await _order.StoreOrderAsync(_cart.GetCartItems(), userId, userEmail);
            await _cart.ClearCartAsync();
            return View("OrderCompleted");
            
        }
    }
}

GoAnime/Controllers/ProducersController.cs
using GoAnime.Core.Interfaces;
using GoAnime.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
        public IActionResult Create() => View();
        
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        public async Task<IActionResult> Details(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePictureURL, Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var details = await _service.GetByIdAsync(id);
            if (details == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

GoAnime/Controllers/StudiosController.cs
using GoAnime.Core.Interfaces;
using GoAnime.Domain.Models;
using GoAnime.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class StudiosController : Controller
    {
        private readonly IStudiosService _service;
        public StudiosController(IStudiosService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, Logo, Description")] Studio studio)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(studio);
                return RedirectToAction(nameof(Index));
            }
            return View(studio);
        }

        public async Task<IActionResult> Details(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Logo, Description")] Studio studio)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, studio);
                return RedirectToAction(nameof(Index));
            }
            return View(studio);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var details = await _service.GetByIdAsync(id);
            if (details == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

GoAnime/Controllers/VoiceActorsController.cs
using GoAnime.Core.Interfaces;
using GoAnime.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class VoiceActorsController : Controller
    {
        private readonly IVoiceActorsService _service;
        public VoiceActorsController(IVoiceActorsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Bio")] VoiceActor voiceActor)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(voiceActor);
                return RedirectToAction(nameof(Index));
            }
            return View(voiceActor);
        }

        public async Task<IActionResult> Details(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }
            
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePictureURL, Bio")] VoiceActor voiceActor)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, voiceActor);
                return RedirectToAction(nameof(Index));
            }
            return View(voiceActor);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var details = await _service.GetByIdAsync(id);
            if (details == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

GoAnime/Views/Anime/Create.cshtml
@model GoAnime.Core.ViewModels.NewAnimeVM
@using GoAnime.Domain.Enums

@{
    ViewData["Title"] = "Create a new anime";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new anime</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="StudioId" class="control-label"></label>
                                <select asp-for="StudioId" class="form-control" asp-items="ViewBag.Studios"></select>
                                <span asp-validation-for="StudioId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AnimeGenre" class="control-label"></label>
                                <select asp-for="AnimeGenre" class="form-control" asp-items="Html.GetEnumSelectList<AnimeGenre>()"></select>
                                <span asp-validation-for="AnimeGenre" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VoiceActorIds" class="control-label"></label>
                                <select asp-for="VoiceActorIds" class="form-control" asp-items="ViewBag.VoiceActors" multiple></select>
                                <span asp-validation-for="VoiceActorIds" class="text-danger"></span>
                            </div>                           
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control" multiple></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img id="ImageURLPreview" class="rounded-circle" src="https://via.placeholder.com/150" style="max-width: 150px">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-primary" asp-action="Index" title="Click to go back to list">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImageURLPreview');
            output.src = $("#ImageURL").val();
        })
        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ImageURLPreview');
            output.src = $(this).val();
        });
    </script>
}

GoAnime/Views/Anime/Details.cshtml
@model GoAnime.Domain.Models.Anime;

@{
    ViewData["Title"] = "Anime details";
}

<div class="row">
    {
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Studio: </b>
                            <a asp-controller="Studios" asp-action="Details" asp-route-id="@Model.StudioId">
                                @Model.Studio.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Genre: </b>@Model.AnimeGenre</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text">
                            <b>Status: </b>
                            @if (DateTime.Now <= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">Upcoming</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">Expired</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">Available</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>VoiceActors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var voiceActor in Model.VoiceActors_Anime)
                                {
                                    <div class="column text-center">
                                        <img src="@voiceActor.VoiceActor.ProfilePictureURL" style="max-width: 150px" class="rounded-circle">
                                        <br />
                                        <a asp-controller="VoiceActors" asp-action="Details" asp-route-id="@voiceActor.VoiceActorId">
                                            @voiceActor.VoiceActor.FullName
                                        </a>
                                    </div>
                                }
                            </div>
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                            Back to List
                            </a>
                            <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddToCart" asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i>
                                Add to Cart (Price @Model.Price.ToString("c", CultureInfo.CreateSpecificCulture("en-US")))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    }
</div>

GoAnime/Views/Anime/Index.cshtml
@model IEnumerable<GoAnime.Domain.Models.Anime>

@{
    ViewData["Title"] = "List of Anime";
}

<div class="row">
    @foreach(var item in Model){
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                      @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                      {                                   
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a> 
                                      }                                   
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Studio: </b>@item.Studio.Name</p>
                            <p class="card-text"><b>Genre: </b>@item.AnimeGenre</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>Status: </b>
                                @if(DateTime.Now <= item.StartDate && DateTime.Now <= item.EndDate){
                                    <span class="badge bg-success text-white">Upcoming</span>
                                }else if(DateTime.Now > item.EndDate){
                                    <span class="badge bg-danger text-white">Expired</span>
                                }else{
                                    <span class="badge bg-primary text-white">Available</span>
                                }
                                </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill">Details</i>
                                </a>
                                <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddToCart" asp-route-id="@item.Id">
                                    Add to Cart (Price @item.Price.ToString("c", CultureInfo.CreateSpecificCulture("en-US")))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@await Html.PartialAsync("_CreateItem", "Anime");