GoAnime/Controllers/AnimeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Linq;
using GoAnime.Core.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using GoAnime.Core.ViewModels;
using System;

namespace GoAnime.Controllers
{
    public class AnimeController : Controller
    {
        private readonly IAnimeService _service;
        public AnimeController(IAnimeService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync(v => v.Studio));
        public async Task<IActionResult> Filter(string searchString) 
        {
            var allAnime = await _service.GetAllAsync(v => v.Studio);
            if (!string.IsNullOrEmpty(searchString))
            {
                var searchResult = allAnime.Where(v => string.Equals(v.Name, searchString, StringComparison.OrdinalIgnoreCase) || string.Equals(v.Description, searchString, StringComparison.OrdinalIgnoreCase) || string.Equals(v.AnimeGenre.ToString(), searchString, StringComparison.OrdinalIgnoreCase)).ToList();
                return View("Index", searchResult);
            }
            return View("Index", allAnime);
        } 

        public async Task<IActionResult> Details(int id) => View(await _service.GetAnimeByIdAsync(id));
        public async Task<IActionResult> Create()
        {
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewAnimeVM anime)
        {
            if (ModelState.IsValid)
            {
                await _service.AddNewAnimeAsync(anime);
                return RedirectToAction(nameof(Index));
            }
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View(anime);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var animeDetails = await _service.GetAnimeByIdAsync(id);
            if (animeDetails == null) return View("NotFound");
            var response = new NewAnimeVM()
            {
                Id = animeDetails.Id,
                Name = animeDetails.Name,
                Description = animeDetails.Description,
                AnimeGenre = animeDetails.AnimeGenre,
                ImageURL = animeDetails.ImageURL,
                Price = animeDetails.Price,
                StartDate = animeDetails.StartDate,
                EndDate = animeDetails.EndDate,
                ProducerId = animeDetails.ProducerId,
                StudioId = animeDetails.StudioId,
                VoiceActorIds = animeDetails.VoiceActors_Anime.Select(v => v.VoiceActorId).ToList()
            };
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewAnimeVM anime)
        {
            if (id != anime.Id) return View("NotFound");
            if (ModelState.IsValid)
            {
                await _service.UpdateAnimeAsync(anime);
                return RedirectToAction(nameof(Index));
            }
            var animeDropdown = await _service.GetNewAnimeDropdownValuesAsync();
            ViewBag.Studios = new SelectList(animeDropdown.Studios, "Id", "Name");
            ViewBag.Producers = new SelectList(animeDropdown.Producers, "Id", "FullName");
            ViewBag.VoiceActors = new SelectList(animeDropdown.VoiceActors, "Id", "FullName");
            return View(anime);
        }
    }
}

GoAnime/Controllers/OrdersController.cs
using GoAnime.Core.CartFunctionality;
using GoAnime.Core.Interfaces;
using GoAnime.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IAnimeService _service;
        private readonly IOrderService _order;
        private readonly Cart _cart;
        public OrdersController(IAnimeService service, Cart cart, IOrderService order)
        {
            _service = service;
            _cart = cart;
            _order = order;
        }
        public async Task<IActionResult> Index() 
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            return View(await _order.GetOrdersByUserIdAndRoleAsync(userId, userRole));
        } 
        public IActionResult Cart() 
        {
            var items = _cart.GetCartItems();
            _cart.CartItems = items;
            var response = new CartVM()
            {
                Cart = _cart,
                CartTotal = _cart.CartTotal()
            };
            return View(response);
        }
        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            var anime = await _service.GetAnimeByIdAsync(id);
            if(anime != null)
            {
                _cart.AddItemToCart(anime);
            }
            return RedirectToAction(nameof(Cart));           
        }

        public async Task<RedirectToActionResult> RemoveFromCart(int id)
        {
            var anime = await _service.GetAnimeByIdAsync(id);
            if (anime != null)
            {
                _cart.RemoveItemFromCart(anime);
            }
            return RedirectToAction(nameof(Cart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);
            await _order.StoreOrderAsync(_cart.GetCartItems(), userId, userEmail);
            await _cart.ClearCartAsync();
            return View("OrderCompleted");
            
        }
    }
}

GoAnime/Controllers/ProducersController.cs
using GoAnime.Core.Interfaces;
using GoAnime.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
        public IActionResult Create() => View();
        
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        public async Task<IActionResult> Details(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePictureURL, Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var details = await _service.GetByIdAsync(id);
            if (details == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

GoAnime/Controllers/StudiosController.cs
using GoAnime.Core.Interfaces;
using GoAnime.Domain.Models;
using GoAnime.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GoAnime.Controllers
{
    public class StudiosController : Controller
    {
        private readonly IStudiosService _service;
        public StudiosController(IStudiosService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, Logo, Description")] Studio studio)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(studio);
                return RedirectToAction(nameof(Index));
            }
            return View(studio);
        }

        public async Task<IActionResult> Details(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Logo, Description")] Studio studio)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, studio);
                return RedirectToAction(nameof(Index));
            }
            return View(studio);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var details = await _service.GetByIdAsync(id);
            return details == null ? View("NotFound") : View(details);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var details = await _service.GetByIdAsync(id);
            if (details == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

GoAnime/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">There is nothing here! Zannen desu</h1>  
        <hr />
        <a class="btn btn-outline-secondary offset-5" href="javascript:history.back()">Go Back</a>
    </div>
</div>

GoAnime/Views/Shared/_CreateItem.cshtml
@model string;

@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed; right: 20px; bottom: 25px; z-index: 1" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle" style="margin-right: 5px"></i>Add New
        </a>
    </div>
}

GoAnime/Views/Shared/_Identity.cshtml
@using GoAnime.Domain.Models
@inject UserManager<AnimeFan> user;

@if(!User.Identity.IsAuthenticated){
    <div style="margin-right: 10px">
        <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
            <i class="bi bi-box-arrow-in-right"></i> Login
        </a>
    </div>
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Sign up
    </a>
}else{
    <div class="dropdown" style="margin-left: 10px">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn"
            data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @user.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list" style="margin-right: 5px"></i>Orders
                </a>
            </li>
            @if(User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-person" style="margin-right: 5px"></i>Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

GoAnime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoAnime</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"style="position: relative;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Anime" asp-action="Index">GoAnime</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Anime" asp-action="Index"><i class="bi bi-film" style="margin-right: 5px"></i>Anime</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear" style="margin-right: 5px"></i>Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Studios" asp-action="Index"><i class="bi bi-camera-reels" style="margin-right: 5px"></i>Studios</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset" style="margin-right: 5px"></i>Producers</a>
                                    <a class="dropdown-item" asp-controller="VoiceActors" asp-action="Index"><i class="bi bi-person-square" style="margin-right: 5px"></i>Voice Actors</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Anime" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control mr-sm-2" placeholder="Search for an anime..." aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("CartSummary")
                    </ul>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GoAnime
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>